### PR TITLE
Some small fixes

### LINKED ISSUE #1095: Wrong warning on useless_vec
Consider following code:
```
struct A;

impl A {
    fn move_self(self) {
        // do something
    }
}

for a in vec![A, A, A] {
    a.move_self()
}
```
Because a need to be moved, so here using a Vector. But clippy will complain:

> ```
warning: useless use of `vec!`, #[warn(useless_vec)] on by default
      for a in vec![A, A, A] {
               ^~~~~~~~~~~~~
help: you can use a slice directly
      for a in &[A, A, A] {
help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#useless_vec
```

### LINKED ISSUE #1098: needless_return suggests Statement instead of Expression
I just played around with rustfix and clippy accidently responds with a trailing semicolon:

```rust
fn test() -> usize {
    return 5;
}

fn main() {
    println!("Hello, world! {}", test());
}
```

```
src\main.rs:2:5: 2:13 warning: unneeded return statement, #[warn(needless_return)] on by default
src\main.rs:2     return 5;
                  ^~~~~~~~
src\main.rs:2:5: 2:13 help: remove `return` as shown:
src\main.rs:      5;
src\main.rs:2:5: 2:13 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_return
```

### PR DESCRIPTION
**Pull request by mcarton**
Fix #1098.
Fix #1095.

### CODE REVIEW

File: clippy_lints/src/utils/mod.rs [hunk 1]
```diff
@@ -723,3 +723,8 @@ pub fn type_is_unsafe_function(ty: ty::Ty) -> bool {
         _ => false,
     }
 }
+
+pub fn is_copy<'a, 'ctx>(cx: &LateContext<'a, 'ctx>, ty: ty::Ty<'ctx>, env: NodeId) -> bool {
```
Comment (llogiq) [inline clippy_lints/src/utils/mod.rs]: Very useful. :+1:

Comment (mcarton) [inline clippy_lints/src/utils/mod.rs]: It was already there, buried in `clippy_lints/src/methods.rs`.
