### PR TITLE
Linting classical overflow checks

### LINKED ISSUE #656: lint failed overflow checks
lint operations in the form `a + b < a` (or b), which is likely a (failed) overflow check. In debug mode, the operation will panic on overflow. Suggest  `wrapping_add(..)`. Same with subtraction and underflow.

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@Manishearth , @mcarton getting a compile error in `cyclomatic_complexity.rs` as follows :- [https://pastebin.mozilla.org/8862490](https://pastebin.mozilla.org/8862490)
Fix #656.

### CODE REVIEW

**Comment by mcarton** [comment]
@martiansideofthemoon Update your nightly

File: src/lib.rs [hunk 1]
```diff
@@ -283,6 +285,7 @@ pub fn plugin_registrar(reg: &mut Registry) {
         needless_update::NEEDLESS_UPDATE,
         no_effect::NO_EFFECT,
         open_options::NONSENSICAL_OPEN_OPTIONS,
+        overflow_check_conditional::OVERFLOW_CHECK_CONDTIONAL,
```
Comment (mcarton) [inline src/lib.rs]: You’re missing an `i` here

File: src/overflow_check_conditional.rs [hunk 2]
```diff
@@ -0,0 +1,41 @@
+use rustc::lint::*;
+use syntax::ast::*;
+use utils::{span_lint, span_help_and_lint, snippet, span_lint_and_then};
+
+/// **What it does:** This lint finds classic overflow checks.
+///
+/// **Why is this bad?** Most classic overflow checks would cause the compiler to panic.
```
Comment (mcarton) [inline src/overflow_check_conditional.rs]: I would reformulate that to insist on the fact that while those are classic in C, they won’t work in Rust. Also point out that Rust does not need them because of the `overflowing_*` and `wrapping_*` family of functions.

File: src/overflow_check_conditional.rs [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    	if_let_chain! {[
+    		let ExprKind::Binary(ref op, ref first, ref second) = expr.node,
+    		let BinOpKind::Lt = op.node,
+    		let ExprKind::Binary(ref op2, ref add1, ref add2) = first.node,
+    		let BinOpKind::Add = op2.node,
+    		let ExprKind::Path(_,ref path1) = add1.node,
+    		let ExprKind::Path(_, ref path2) = add2.node,
+    		let ExprKind::Path(_, ref path3) = second.node
+    	], {
+    		if ((&path1.segments[0]).identifier == (&path3.segments[0]).identifier) ||
```
Comment (mcarton) [inline src/overflow_check_conditional.rs]: You can add non-let conditional in `if_let_chain` (and that’s what we do on other lints):
```rust
if_let_chain! {[
    let ExprKind::Path(_, ref path3) = second.node,
    ((&path1.segments[0]).identifier == (&path3.segments[0]).identifier) || …
], {
}}
```

File: src/overflow_check_conditional.rs [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+    		((&path2.segments[0]).identifier == (&path3.segments[0]).identifier) {
+        		// Some lint
+        	}
```
Comment (mcarton) [inline src/overflow_check_conditional.rs]: Clippy uses 4-spaces, not tabs.

File: tests/compile-fail/overflow_check_conditional.rs [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+#![plugin(clippy)]
+
+#![deny(overflow_check_conditional)]
+
+fn main() {
+	let a: u32 = 1;
+	let b: u32 = 2;
+	if a + b < a {
+
+	}
```
Comment (mcarton) [inline tests/compile-fail/overflow_check_conditional.rs]: We you write a test, add things that are similar but should not lint, eg. `a + b < c`. Also `a + b < c` should lint as well.

File: src/overflow_check_conditional.rs [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+    		let BinOpKind::Lt = op.node,
+    		let ExprKind::Binary(ref op2, ref add1, ref add2) = first.node,
+    		let BinOpKind::Add = op2.node,
+    		let ExprKind::Path(_,ref path1) = add1.node,
+    		let ExprKind::Path(_, ref path2) = add2.node,
+    		let ExprKind::Path(_, ref path3) = second.node
+    	], {
+    		if ((&path1.segments[0]).identifier == (&path3.segments[0]).identifier) ||
+    		((&path2.segments[0]).identifier == (&path3.segments[0]).identifier) {
+        		// Some lint
```
Comment (mcarton) [inline src/overflow_check_conditional.rs]: You must check the type of the operands here (search for `expr_ty` in Clippy) and lint only for integers.

File: tests/compile-fail/overflow_check_conditional.rs (hunk 5 above)
Comment (martiansideofthemoon) [inline tests/compile-fail/overflow_check_conditional.rs]: `a + b < c` should lint as well?

Comment (mcarton) [inline tests/compile-fail/overflow_check_conditional.rs]: No, but you should add it in the test file to ensure it does not. (the test suite checks that only line with a `//~ERROR` trigger errors, so just add something with `a + b < c` with no such comment)

Comment (martiansideofthemoon) [inline tests/compile-fail/overflow_check_conditional.rs]: Oh alright, will do it in sometime :smile:

Comment (mcarton) [inline tests/compile-fail/overflow_check_conditional.rs]: Oh I see, I meant « Also `a + b < b` should lint as well. » :smile:

Comment (martiansideofthemoon) [inline tests/compile-fail/overflow_check_conditional.rs]: @mcarton yeah was talking about that :smile: Getting this error while compiling [https://pastebin.mozilla.org/8862494](https://pastebin.mozilla.org/8862494). Should I remove `use syntax::ast::*;` completely? What's the difference between the two?

Comment (mcarton) [inline tests/compile-fail/overflow_check_conditional.rs]: Rustc has several types of AST for different step of compilation. The `ast::*` stuff is just for `EarlyLintPass`s and has no type information yet, you need to use `hir::*` stuffs and a `LateLintPass` which use slightly different names for everything since a few weeks (usually when `ast` has `FooKind::Bar`, `hir` has `FooBar`). You won’t need `ast::*` stuffs here.

**Comment by martiansideofthemoon** [comment]
@Manishearth , @mcarton I hope it's okay :smile:

File: src/overflow_check_conditional.rs [hunk 7]
```diff
@@ -0,0 +1,41 @@
+use rustc::lint::*;
+use rustc_front::hir::*;
+use utils::{span_lint, span_help_and_lint, snippet, span_lint_and_then};
+
+/// **What it does:** This lint finds classic overflow checks.
+///
+/// **Why is this bad?** Most classic C overflow checks will fail in Rust. Users can use functions like overflowing_* and wrapping_* instead.
```
Comment (mcarton) [inline src/overflow_check_conditional.rs]: Can you put `overflowing_*` and `wrapping_*` between quotes? Looks better on the wiki.
```markdown
`overflowing_*` and `wrapping_*`
```

File: tests/compile-fail/overflow_check_conditional.rs [hunk 8]
```diff
@@ -0,0 +1,22 @@
+#![feature(plugin)]
+#![plugin(clippy)]
+
+#![deny(overflow_check_conditional)]
+
+fn main() {
+	let a: u32 = 1;
+	let b: u32 = 2;
+	let c: u32 = 3;
+	if a + b < a { //~ERROR You are trying to use classic C overflow conditons that will fail in Rust.
```
Comment (mcarton) [inline tests/compile-fail/overflow_check_conditional.rs]: `a + b < b` should be tested as well.

**Comment by mcarton** [comment]
You need to run `python util/update_lints.py` to fix the error, you also have an “unused import” warning. Also can you squash your commits together if you know how to?

**Comment by llogiq** [comment]
For bonus points, you could also lint underflow checks, e.g `a - b > a` or `a - b > b`.

**Comment by martiansideofthemoon** [comment]
@llogiq I hope it's okay :smile:

**Comment by llogiq** [comment]
Bonus points for you! :smile: My only small nit is that the lint docs could tell that we lint over- and underflow checks. Also perhaps one could unify some parts into a function to avoid duplication, but I'm fine with merging as it is.

**Comment by mcarton** [comment]
As discussed on IRC, don’t merge the PR yet. He‘ll also handle `a < a - b` not just `a - b > a` tomorrow.

**Comment by llogiq** [comment]
Even better, although those forms are much less common IIRC.

**Comment by martiansideofthemoon** [comment]
@Manishearth , @llogiq , @mcarton I hope it is alright

**Comment by llogiq** [comment]
Unfortunately, it fails the cyclomatic_complexity check. You could factor out some common expressions of both check blocks.

**Comment by oli-obk** [comment]
I've looked at the code, it shouldn't trigger cc, I'll investigate, just throw an `allow(cyclomatic_complexity)` on your function and I'll fix the lint

**Comment by martiansideofthemoon** [comment]
@oli-obk alright, thanks I'll do it in a bit :smile:

**Comment by martiansideofthemoon** [comment]
@llogiq , @oli-obk , @mcarton I've written the `allow`

**Comment by llogiq** [comment]
Thanks! Good work :+1:
