### PR TITLE
Fix some false positive in needless_lifetimes lint

### LINKED ISSUE #417: False positive for needless_lifetimes
While working on https://github.com/Manishearth/rust-clippy/pull/396 I ran into a false positive for the `needless_lifetimes` lint. A small example:

```rust
pub struct Foo<'a> {
    r: &'a str
}

fn do_foo<'a>(foo: &'a Foo) -> &'a str { // compiles, but clippy warns
//fn do_foo(foo: &Foo) -> &str { // doesn't compile (missing lifetime specifier)
    foo.r
}

fn main() { do_foo(&Foo {r: "hello" }); }
```

When running clippy on this code, it gives
```
src/main.rs:5:1: 8:2 warning: explicit lifetimes given in parameter types where they could be elided, #[warn(needless_lifetimes)] on by default
```
but after removing the explicit lifetimes, rustc fails with the following error:
```
src/main.rs:6:25: 6:29 error: missing lifetime specifier [E0106]
src/main.rs:6 fn do_foo(foo: &Foo) -> &str {
```

### PR DESCRIPTION
**Pull request by fhartwig**
Fixes #417

The current lifetime-collecting visitor in `needless_lifetimes` doesn't take into account elided lifetimes on structs, enums or trait objects when collecting input and output lifetimes, which can lead to false positives. These changes fix it to consider these elided lifetimes as well.

One problem that I couldn't figure out is how to look up the definitions for type (and trait) aliases, which I would need to do to make this work with type aliases in function argument and return types as well. Any hints would be appreciated (although this PR should already strictly, and significantly, decrease the number of false positives).

### CODE REVIEW

**Comment by Manishearth** [comment]
\o/ thanks! :cake: 

reviewing now

File: src/lifetimes.rs [hunk 1]
```diff
@@ -159,35 +157,75 @@ fn unique_lifetimes(lts: &[RefLt]) -> usize {
...
-        if let TyRptr(None, _) = ty.node {
-            self.record(&None);
+        match ty.node {
+            TyRptr(None, _) => {
+                self.record(&None);
+            },
+            TyPath(_, ref path) => {
+                self.collect_anonymous_lifetimes(path, ty);
+            },
+            _ => {}
```
Comment (Manishearth) [inline src/lifetimes.rs]: We should bail if there is a `TyObjectSum`

**Comment by Manishearth** [comment]
This looks great to me, minor changes.

File: src/lifetimes.rs (hunk 1 above)
Comment (fhartwig) [inline src/lifetimes.rs]: What is the problem with those? I've tested this on functions with trait object arguments, and I haven't noticed any problems.

**Comment by llogiq** [comment]
I think we may want more test cases to see at a glance what works and what doesn't.

**Comment by fhartwig** [comment]
@llogiq I'm happy to add more test cases. Any case in particular that you think is missing?

File: src/lifetimes.rs (hunk 1 above)
Comment (Manishearth) [inline src/lifetimes.rs]: It's an extra lifetime position with some strange rules around it IIRC.

Comment (fhartwig) [inline src/lifetimes.rs]: Ok. Since I don't think this PR makes the situation regarding those any worse than it is right now (or does it?), I'd rather do this separately.

**Comment by llogiq** [comment]
I think we could do with more tests where lifetimes are only partially specified. But we can do this in a followup.

r+
