### PR TITLE
Fix various false positives around needless_lifetime

### LINKED ISSUE #292: needless_lifetimes ignores trait bounds
`fn foo<'a, T: Foo<'a>>(&'a u8, T)` will hit the lint. It shouldn't, whenever we have lifetimes in trait bounds we should bail.

### LINKED ISSUE #740: False positive for `needless_lifetimes`
Here's a trivial example that should trigger it. Removing the lifetime annotations causes the code not to compile (`cannot infer an appropriate lifetime ...`), but clippy gives a `needless_lifetimes` warning.

``` rust
struct Test {
    vec: Vec<usize>,
}

impl Test {
    fn iter<'a>(&'a self) -> Box<Iterator<Item = usize> + 'a> {
        Box::new(self.vec.iter().cloned())
    }
}
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #292 
fixes #740

### CODE REVIEW

**Comment by oli-obk** [comment]
I'll publish a new version as soon as someone reviews this.

No tests have been harmed in the writing of this PR

New false negatives will exist when multiple lifetimes are used. Fixing these false negatives is incredibly hard. The rustc code around all of those is insane!

File: clippy_lints/src/lifetimes.rs [hunk 1]
```diff
@@ -384,3 +415,20 @@ fn report_extra_lifetimes<'a, 'tcx: 'a>(cx: &LateContext<'a, 'tcx>, func: &'tcx
...
+    fn visit_lifetime(&mut self, lifetime: &'tcx Lifetime) {
+        if lifetime.name != keywords::Invalid.name() && lifetime.name != "'static" {
+            self.lifetimes_used_in_body = true;
+        }
+    }
+
+    fn nested_visit_map<'this>(&'this mut self) -> NestedVisitorMap<'this, 'tcx> {
+        NestedVisitorMap::None
+    }
+}
```
Comment (Manishearth) [inline clippy_lints/src/lifetimes.rs]: newline

**Comment by Manishearth** [comment]
r+ | nit
