### PR TITLE
fix explicit_into_iter_loop on references

### LINKED ISSUE #1398: False positive for `into_iter` rule
Calling [`Itertools::chunks`](https://docs.rs/itertools/*/itertools/trait.Itertools.html#method.chunks) returns a [`IntoChunks`](https://docs.rs/itertools/*/itertools/structs/struct.IntoChunks.html) with `impl<'a> IntoIterator for &'a IntoChunks`

```rust
for records_iter in some_iterator.chunks().into_iter() { ... }
```

works while

```rust
for records_iter in some_iterator.chunks() { ... }
```

fails with

```rust
error[E0277]: the trait bound `itertools::IntoChunks<T>: std::iter::Iterator` is
 not satisfied
[…]
    = note: `itertools::IntoChunks<T>` is not an iterator; maybe try calling `.i
ter()` or a similar method
    = note: required by `std::iter::IntoIterator::into_iter`
```

### LINKED ISSUE #1493: explicit_iter_loop warning message not helpful enough to fix the issue
In the following code: 

```rust
fn u8_runner<F: Fn(u8) -> u8>(bench: &mut Bencher, f: F) {
    let mut vs = (0..u8::max_value()).collect::<Vec<_>>();
    bench.iter(|| {
        for mut v in vs.iter_mut() {
            *v = bencher::black_box(f(bencher::black_box(*v)));
        }
    })
}
```

I get the following lint: 

> `warning: it is more idiomatic to loop over `&mut vs` instead of `vs.iter_mut()`, #[warn(explicit_iter_loop)] on by default`

From this it is not clear at all what clippy wants for me. 

I've tried 

```rust
fn u8_runner<F: Fn(u8) -> u8>(bench: &mut Bencher, f: F) {
    let mut vs = (0..u8::max_value()).collect::<Vec<_>>();
    bench.iter(|| {
        for &mut v in vs {
            *v = bencher::black_box(f(bencher::black_box(*v)));
        }
    })
}
```

and 

```rust
fn u8_runner<F: Fn(u8) -> u8>(bench: &mut Bencher, f: F) {
    let mut vs = (0..u8::max_value()).collect::<Vec<_>>();
    bench.iter(|| {
        for &mut v in vs.iter() {
            *v = bencher::black_box(f(bencher::black_box(*v)));
        }
    })
}
```

without any luck. Reading [the online description](ttps://github.com/Manishearth/rust-clippy/wiki#explicit_iter_loop) was not helpful. Maybe clippy should really tell me what the X, Y, and Z in the following snippet should look like:

```rust
fn u8_runner<F: Fn(u8) -> u8>(bench: &mut Bencher, f: F) {
    let mut vs = (0..u8::max_value()).collect::<Vec<_>>();
    bench.iter(|| {
        for X?? in Y?? {
            Z?? = bencher::black_box(f(bencher::black_box(Z??)));
        }
    })
}
```

where:

- X is the iteration variable,
- Y is what i am iterating on,
- Z is how I am accessing the value.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #1398 
fixes #1493

rebase of other PR

### CODE REVIEW

File: clippy_lints/src/loops.rs [hunk 1]
```diff
@@ -578,48 +578,55 @@ fn check_for_loop_reverse_range(cx: &LateContext, arg: &Expr, expr: &Expr) {
...
+    } else {
+        ""
+    };
+    span_lint_and_sugg(cx,
+                       EXPLICIT_ITER_LOOP,
+                       arg.span,
+                       "it is more idiomatic to loop over references to containers instead of using explicit \
+                        iteration methods",
+                       "to write this more concisely, try looping over",
+                       format!("&{}{}", muta, object))
```
Comment (mcarton) [inline clippy_lints/src/loops.rs]: Doesn't that make a weird suggestion?

File: clippy_lints/src/utils/mod.rs [hunk 2]
```diff
@@ -563,6 +563,17 @@ pub fn span_lint_and_then<'a, 'tcx: 'a, T: LintContext<'tcx>, F>(
...
 
+pub fn span_lint_and_sugg<'a, 'tcx: 'a, T: LintContext<'tcx>>(
+    cx: &'a T,
+    lint: &'static Lint,
+    sp: Span,
+    msg: &str,
+    help: &str,
+    sugg: String
+) {
+    span_lint_and_then(cx, lint, sp, msg, |db| { db.span_suggestion(sp, help, sugg); });
```
Comment (mcarton) [inline clippy_lints/src/utils/mod.rs]: Why the `{;}`?

Comment (oli-obk) [inline clippy_lints/src/utils/mod.rs]: because we expect the closure to not return a `db` object, but all the methods on `db` return a reference to it.

File: clippy_lints/src/loops.rs (hunk 1 above)
Comment (oli-obk) [inline clippy_lints/src/loops.rs]: as you can see in the tests, none of the suggestions changed.

Comment (mcarton) [inline clippy_lints/src/loops.rs]: But the tests are not ui-tests. The suggestion was included after “over”, now that “try looping over” will be followed by the whole line of the replacement.
We'll have something like
```rust
help: try looping over
  |     for foo in &bar {
  | }
```
