### PR TITLE
Revert "Automatically defines the `clippy` feature"

### LINKED ISSUE #1055: cargo-clippy's "clippy" feature flag collides with dependencies using their own "clippy" feature
I was just playing with [syntect](https://github.com/trishume/syntect) and compiled it with `cargo clippy`. Sadly, this breaks while compiling yaml-rust 0.3.3:

```plain
   Compiling serde v0.7.11
   Compiling yaml-rust v0.3.3
/Users/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/yaml-rust-0.3.3/src/lib.rs:40:38: 40:44 error: can't find crate for `clippy` [E0463]
/Users/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/yaml-rust-0.3.3/src/lib.rs:40 #![cfg_attr(feature="clippy", plugin(clippy))]
[package]
                                                                                                                                 ^~~~~~
error: aborting due to previous error
```

It looks to me like `cargo clippy` adds the "clippy" feature -- but not just to the current crate but to dependencies as well. yaml-rust has a "compile with clippy" mode on its own (see its [Cargo.toml](https://github.com/chyh1990/yaml-rust/blob/bcb0c6e588f9afcc3013242b8dbe95e34ba65cc0/Cargo.toml)). Don't ask me why setting the feature doesn't trigger clippy (as dep) to be included in yaml-rust, though…

### PR DESCRIPTION
**Pull request by mcarton**
This reverts commit d7ba66bf44f993e64114e17cc15f1b0d56ae8f70.

It was causing problems with crates with:

```rust
#![cfg_attr(feature="clippy", plugin(clippy))]
```

Close #1055.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -149,14 +149,11 @@ pub fn main() {
...
         }
     } else {
-        let mut args: Vec<String> = if env::args().any(|s| s == "--sysroot") {
+        let args: Vec<String> = if env::args().any(|s| s == "--sysroot") {
             env::args().collect()
         } else {
             env::args().chain(Some("--sysroot".to_owned())).chain(Some(sys_root)).collect()
         };
-
-        args.extend_from_slice(&["--cfg".to_owned(), r#"feature="clippy""#.to_owned()]);
```
Comment (oli-obk) [inline src/main.rs]: I think it's enough to leave out this line

File: src/main.rs [hunk 2]
```diff
@@ -187,8 +184,6 @@ fn process<P, I>(old_args: I, dep_path: P, sysroot: &str) -> Result<(), i32>
     args.push(String::from("--sysroot"));
     args.push(sysroot.to_owned());
     args.push("-Zno-trans".to_owned());
-    args.push("--cfg".to_owned());
-    args.push(r#"feature="clippy""#.to_owned());
```
Comment (oli-obk) [inline src/main.rs]: because this line is only applied to the `cargo rustc` call, which doesn't forward to all dependencies, but just to the last invocation

Comment (mcarton) [inline src/main.rs]: The problem also happens when something like `#![cfg_attr(feature="clippy", plugin(clippy))]` is in not in a dependency but directly in the crate.

Comment (oli-obk) [inline src/main.rs]: right... we can't assume that it's either plugin or cargo-clippy, could be both

**Comment by crumblingstatue** [comment]
Aww man, I started utilizing this feature.

Is it possible to bring this feature back in some form in the future?
Like defining feature=cargo-clippy or something.

**Comment by crumblingstatue** [comment]
Hrm. I guess I can add an empty `[features] clippy = []` to my Cargo.toml, and enable the feature manually when running clippy with `cargo clippy --features=clippy`

**Comment by mcarton** [comment]
Yeah, the point was to not have people have to do that manually but it's easy to do.
The problem was that people were already using the name “clippy” for something slightly different. Maybe we could bring it back under another name that people don't already use :+1:.
