### PR TITLE
rustup to 2017-01-12

### LINKED ISSUE #1440: Fails to compile under rustc 1.16.0-nightly (2782e8f8f 2017-01-12)
clippy_lints 0.0.107 fails to build under rustc 1.16.0-nightly (2782e8f8f 2017-01-12), x86_64 on Linux.

Build log as follows:

<details>

```
ajd@ajd:~$ rustup run nightly cargo install clippy                  
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustc-serialize v0.3.22
   Compiling regex-syntax v0.4.0
   Compiling matches v0.1.4
   Compiling unicode-normalization v0.1.3
   Compiling quine-mc_cluskey v0.2.4
   Compiling nom v1.2.4
   Compiling semver v0.2.3
   Compiling toml v0.1.30
   Compiling clippy_lints v0.0.107
error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/array_indexing.rs:5:5
  |
5 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:12:5
   |
12 | use rustc_const_eval::eval_const_expr_partial;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:6:5
  |
6 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:7:5
  |
7 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:8:5
  |
8 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/regex.rs:6:5
  |
6 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:1069:9
     |
1069 |     use rustc_const_eval::eval_const_expr_partial;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0432]: unresolved import `rustc_const_eval::eval_const_expr_partial`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/vec.rs:5:5
  |
5 | use rustc_const_eval::eval_const_expr_partial;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eval_const_expr_partial` in the root

error[E0425]: unresolved function `eval_const_expr_partial`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/enum_clike.rs:47:37
   |
47 |                     let bad = match eval_const_expr_partial(cx.tcx,
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^ no resolution found

error[E0425]: unresolved function `eval_const_expr_partial`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:879:20
    |
879 |     let cv = match eval_const_expr_partial(cx.tcx, expr, ExprTypeChecked, None) {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^ no resolution found

error: use of unstable library feature 'i128' (see issue #35118)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:892:49
    |
892 |         (&ty::TyInt(IntTy::I128), Integral(I128(::std::i128::MIN))) |
    |                                                 ^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(i128)] to the crate attributes to enable

error: use of unstable library feature 'i128' (see issue #35118)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:899:51
    |
899 |         (&ty::TyUint(UintTy::U128), Integral(U128(::std::u128::MIN))) => Minimum,
    |                                                   ^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(i128)] to the crate attributes to enable

error: use of unstable library feature 'i128' (see issue #35118)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:908:49
    |
908 |         (&ty::TyInt(IntTy::I128), Integral(I128(::std::i128::MAX))) |
    |                                                 ^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(i128)] to the crate attributes to enable

error: use of unstable library feature 'i128' (see issue #35118)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:915:51
    |
915 |         (&ty::TyUint(UintTy::U128), Integral(U128(::std::u128::MAX))) => Maximum,
    |                                                   ^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(i128)] to the crate attributes to enable

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/consts.rs:298:31
    |
298 |             let def = lcx.tcx.tables().qpath_def(qpath, id);
    |                               ^^^^^^
    |
note: did you mean to write `lcx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/consts.rs:298:31
    |
298 |             let def = lcx.tcx.tables().qpath_def(qpath, id);
    |                               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/consts.rs:303:26
    |
303 |                         .tables()
    |                          ^^^^^^
    |
note: did you mean to write `lcx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/consts.rs:303:26
    |
303 |                         .tables()
    |                          ^^^^^^

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/consts.rs:306:33
    |
306 |                     if let Some((const_expr, _ty)) = lookup_const_by_id(lcx.tcx, def_id, substs) {
    |                                 ^^^^^^^^^^^^^^^^^ expected a tuple with 3 elements, found one with 2 elements
    |
    = note: expected type `(&rustc::hir::Expr, core::option::Option<&rustc::ty::Tables<'_>>, core::option::Option<&rustc::ty::TyS<'_>>)`
    = note:    found type `(_, _)`

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/inspector.rs:141:58
    |
141 |             println!("local variable of type {}", cx.tcx.tables().node_id_to_type(local.id));
    |                                                          ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/inspector.rs:141:58
    |
141 |             println!("local variable of type {}", cx.tcx.tables().node_id_to_type(local.id));
    |                                                          ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/inspector.rs:155:21
    |
155 |     let ty = cx.tcx.tables().node_id_to_type(expr.id);
    |                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/inspector.rs:155:21
    |
155 |     let ty = cx.tcx.tables().node_id_to_type(expr.id);
    |                     ^^^^^^

error: no field `method_map` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:188:10
    |
188 |         .method_map
    |          ^^^^^^^^^^ unknown field

error: no field `method_map` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:205:10
    |
205 |         .method_map
    |          ^^^^^^^^^^ unknown field

error[E0061]: this function takes 2 parameters but 3 parameters were supplied
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:330:23
    |
330 |     cx.tcx.infer_ctxt(None, None, Reveal::All).enter(|infcx| {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:339:12
    |
339 |     cx.tcx.tables().qpath_def(qpath, id)
    |            ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:339:12
    |
339 |     cx.tcx.tables().qpath_def(qpath, id)
    |            ^^^^^^

error: no field `adjustments` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:625:28
    |
625 |     cx.tcx.tables.borrow().adjustments.get(&e.id).is_some()
    |                            ^^^^^^^^^^^ unknown field

error[E0061]: this function takes 2 parameters but 3 parameters were supplied
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:790:23
    |
790 |     cx.tcx.infer_ctxt(None, Some(parameter_env), Reveal::All).enter(|infcx| {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:814:25
    |
814 |         matches!(cx.tcx.tables().qpath_def(qpath, did),
    |                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/utils/mod.rs:814:25
    |
814 |         matches!(cx.tcx.tables().qpath_def(qpath, did),
    |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:62:44
   |
62 |                 let (l_ty, r_ty) = (cx.tcx.tables().expr_ty(l), cx.tcx.tables().expr_ty(r));
   |                                            ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:62:44
   |
62 |                 let (l_ty, r_ty) = (cx.tcx.tables().expr_ty(l), cx.tcx.tables().expr_ty(r));
   |                                            ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:62:72
   |
62 |                 let (l_ty, r_ty) = (cx.tcx.tables().expr_ty(l), cx.tcx.tables().expr_ty(r));
   |                                                                        ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:62:72
   |
62 |                 let (l_ty, r_ty) = (cx.tcx.tables().expr_ty(l), cx.tcx.tables().expr_ty(r));
   |                                                                        ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:72:33
   |
72 |                 let ty = cx.tcx.tables().expr_ty(arg);
   |                                 ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/arithmetic.rs:72:33
   |
72 |                 let ty = cx.tcx.tables().expr_ty(arg);
   |                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/array_indexing.rs:62:29
   |
62 |             let ty = cx.tcx.tables().expr_ty(array);
   |                             ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/array_indexing.rs:62:29
   |
62 |             let ty = cx.tcx.tables().expr_ty(array);
   |                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:85:45
   |
85 |                             let ty = cx.tcx.tables().expr_ty(assignee);
   |                                             ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:85:45
   |
85 |                             let ty = cx.tcx.tables().expr_ty(assignee);
   |                                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:89:46
   |
89 |                             let rty = cx.tcx.tables().expr_ty(rhs);
   |                                              ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:89:46
   |
89 |                             let rty = cx.tcx.tables().expr_ty(rhs);
   |                                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:120:41
    |
120 |                         let ty = cx.tcx.tables().expr_ty(assignee);
    |                                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:120:41
    |
120 |                         let ty = cx.tcx.tables().expr_ty(assignee);
    |                                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:124:42
    |
124 |                         let rty = cx.tcx.tables().expr_ty(rhs);
    |                                          ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/assign_ops.rs:124:42
    |
124 |                         let rty = cx.tcx.tables().expr_ty(rhs);
    |                                          ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/bit_mask.rs:249:30
    |
249 |             let def = cx.tcx.tables().qpath_def(qpath, lit.id);
    |                              ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/bit_mask.rs:249:30
    |
249 |             let def = cx.tcx.tables().qpath_def(qpath, lit.id);
    |                              ^^^^^^

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/bit_mask.rs:251:68
    |
251 |                 lookup_const_by_id(cx.tcx, def_id, None).and_then(|(l, _ty)| fetch_int_literal(cx, l))
    |                                                                    ^^^^^^^^ expected a tuple with 3 elements, found one with 2 elements
    |
    = note: expected type `(&rustc::hir::Expr, core::option::Option<&rustc::ty::Tables<'_>>, core::option::Option<&rustc::ty::TyS<'_>>)`
    = note:    found type `(_, _)`

error: no field `node_types` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/booleans.rs:397:48
    |
397 |                 if self.cx.tcx.tables.borrow().node_types[&inner.id].is_bool() {
    |                                                ^^^^^^^^^^ unknown field

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/copies.rs:266:37
    |
266 |                     v.insert(cx.tcx.tables().pat_ty(pat));
    |                                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/copies.rs:266:37
    |
266 |                     v.insert(cx.tcx.tables().pat_ty(pat));
    |                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/cyclomatic_complexity.rs:67:29
   |
67 |         let ret_ty = cx.tcx.tables().node_id_to_type(expr.id);
   |                             ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/cyclomatic_complexity.rs:67:29
   |
67 |         let ret_ty = cx.tcx.tables().node_id_to_type(expr.id);
   |                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/cyclomatic_complexity.rs:142:38
    |
142 |                 let ty = self.cx.tcx.tables().node_id_to_type(callee.id);
    |                                      ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/cyclomatic_complexity.rs:142:38
    |
142 |                 let ty = self.cx.tcx.tables().node_id_to_type(callee.id);
    |                                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/drop_forget_ref.rs:64:33
   |
59 |         if_let_chain!{[
   |         - in this macro invocation
...
64 |             let def_id = cx.tcx.tables().qpath_def(qpath, path.id).def_id();
   |                                 ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/drop_forget_ref.rs:64:33
   |
59 |         if_let_chain!{[
   |         - in this macro invocation
...
64 |             let def_id = cx.tcx.tables().qpath_def(qpath, path.id).def_id();
   |                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/drop_forget_ref.rs:79:33
   |
59 |         if_let_chain!{[
   |         - in this macro invocation
...
79 |             let arg_ty = cx.tcx.tables().expr_ty(arg);
   |                                 ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/drop_forget_ref.rs:79:33
   |
59 |         if_let_chain!{[
   |         - in this macro invocation
...
79 |             let arg_ty = cx.tcx.tables().expr_ty(arg);
   |                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/entry.rs:92:42
    |
85  |     if_let_chain! {[
    |     - in this macro invocation
...
92  |         let obj_ty = walk_ptrs_ty(cx.tcx.tables().expr_ty(map));
    |                                          ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/entry.rs:92:42
    |
85  |     if_let_chain! {[
    |     - in this macro invocation
...
92  |         let obj_ty = walk_ptrs_ty(cx.tcx.tables().expr_ty(map));
    |                                          ^^^^^^

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/escape.rs:82:53
   |
82 |         let infcx = cx.tcx.borrowck_fake_infer_ctxt(param_env);
   |                                                     ^^^^^^^^^ expected struct `rustc::hir::BodyId`, found struct `rustc::ty::ParameterEnvironment`
   |
   = note: expected type `rustc::hir::BodyId`
   = note:    found type `rustc::ty::ParameterEnvironment<'_>`

error: no field `adjustments` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/escape.rs:167:26
    |
167 |                         .adjustments
    |                          ^^^^^^^^^^^ unknown field

error: no field `adjustments` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/escape.rs:184:30
    |
184 |                             .adjustments
    |                              ^^^^^^^^^^^ unknown field

error[E0061]: this function takes 2 parameters but 3 parameters were supplied
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/escape.rs:212:37
    |
212 |                 self.tcx.infer_ctxt(None, None, Reveal::All).enter(|infcx| {
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eta_reduction.rs:64:32
   |
64 |             let fn_ty = cx.tcx.tables().expr_ty(caller);
   |                                ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eta_reduction.rs:64:32
   |
64 |             let fn_ty = cx.tcx.tables().expr_ty(caller);
   |                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:68:46
   |
68 |                             let var = cx.tcx.tables().qpath_def(qpath, lhs.id).def_id();
   |                                              ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:68:46
   |
68 |                             let var = cx.tcx.tables().qpath_def(qpath, lhs.id).def_id();
   |                                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:129:35
    |
129 |                 match self.cx.tcx.tables().expr_ty(func).sty {
    |                                   ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:129:35
    |
129 |                 match self.cx.tcx.tables().expr_ty(func).sty {
    |                                   ^^^^^^

error: no field `method_map` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:142:50
    |
142 |                 let method_type = borrowed_table.method_map.get(&method_call).expect("This should never happen.");
    |                                                  ^^^^^^^^^^ unknown field

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:305:64
    |
305 |                     if path.segments.len() == 1 && self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id() == self.var {
    |                                                                ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/eval_order_dependence.rs:305:64
    |
305 |                     if path.segments.len() == 1 && self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id() == self.var {
    |                                                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/format.rs:133:38
    |
119 |     if_let_chain! {[
    |     - in this macro invocation
...
133 |         let ty = walk_ptrs_ty(cx.tcx.tables().pat_ty(&pat[0]));
    |                                      ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/format.rs:133:38
    |
119 |     if_let_chain! {[
    |     - in this macro invocation
...
133 |         let ty = walk_ptrs_ty(cx.tcx.tables().pat_ty(&pat[0]));
    |                                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/functions.rs:178:38
    |
178 |                 let ty = self.cx.tcx.tables().expr_ty(f);
    |                                      ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/functions.rs:178:38
    |
178 |                 let ty = self.cx.tcx.tables().expr_ty(f);
    |                                      ^^^^^^

error: no field `method_map` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/functions.rs:188:61
    |
188 |                 let base_type = self.cx.tcx.tables.borrow().method_map[&method_call].ty;
    |                                                             ^^^^^^^^^^ unknown field

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/functions.rs:210:35
    |
210 |             let def = self.cx.tcx.tables().qpath_def(qpath, ptr.id);
    |                                   ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/functions.rs:210:35
    |
210 |             let def = self.cx.tcx.tables().qpath_def(qpath, ptr.id);
    |                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/len_zero.rs:206:35
    |
206 |     let ty = &walk_ptrs_ty(cx.tcx.tables().expr_ty(expr));
    |                                   ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/len_zero.rs:206:35
    |
206 |     let ty = &walk_ptrs_ty(cx.tcx.tables().expr_ty(expr));
    |                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/let_if_seq.rs:140:36
    |
138 |           if_let_chain! {[
    |  _________- starting here...
139 | |             let hir::ExprPath(ref qpath) = expr.node,
140 | |             self.id == self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id(),
    | |                                    ^^^^^^
141 | |         ], {
142 | |             self.used = true;
143 | |             return;
144 | |         }}
    | |__________- ...ending here: in this macro invocation
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/let_if_seq.rs:140:36
    |
138 |           if_let_chain! {[
    |  _________- starting here...
139 | |             let hir::ExprPath(ref qpath) = expr.node,
140 | |             self.id == self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id(),
    | |                                    ^^^^^^
141 | |         ], {
142 | |             self.used = true;
143 | |             return;
144 | |         }}
    | |__________- ...ending here: in this macro invocation

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/let_if_seq.rs:163:24
    |
157 |     if_let_chain! {[
    |     - in this macro invocation
...
163 |         decl == cx.tcx.tables().qpath_def(qpath, var.id).def_id(),
    |                        ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/let_if_seq.rs:163:24
    |
157 |     if_let_chain! {[
    |     - in this macro invocation
...
163 |         decl == cx.tcx.tables().qpath_def(qpath, var.id).def_id(),
    |                        ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'v, 't, 't>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/lifetimes.rs:249:35
    |
249 |                 match self.cx.tcx.tables().qpath_def(qpath, ty.id) {
    |                                   ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/lifetimes.rs:249:35
    |
249 |                 match self.cx.tcx.tables().qpath_def(qpath, ty.id) {
    |                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:630:21
    |
630 |     let ty = cx.tcx.tables().expr_ty(arg);
    |                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:630:21
    |
630 |     let ty = cx.tcx.tables().expr_ty(arg);
    |                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:716:64
    |
716 |             let (new_pat_span, kind, ty, mutbl) = match cx.tcx.tables().expr_ty(arg).sty {
    |                                                                ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:716:64
    |
716 |             let (new_pat_span, kind, ty, mutbl) = match cx.tcx.tables().expr_ty(arg).sty {
    |                                                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:803:60
    |
803 |                 if path.segments.len() == 1 && self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id() == self.var {
    |                                                            ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:803:60
    |
803 |                 if path.segments.len() == 1 && self.cx.tcx.tables().qpath_def(qpath, expr.id).def_id() == self.var {
    |                                                            ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:812:47
    |
805 |                     if_let_chain! {[
    |                     - in this macro invocation
...
812 |                         let def = self.cx.tcx.tables().qpath_def(seqpath, seqexpr.id);
    |                                               ^^^^^^
    |
note: did you mean to write `self.cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:812:47
    |
805 |                     if_let_chain! {[
    |                     - in this macro invocation
...
812 |                         let def = self.cx.tcx.tables().qpath_def(seqpath, seqexpr.id);
    |                                               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:891:21
    |
891 |     let ty = cx.tcx.tables().expr_ty(e);
    |                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:891:21
    |
891 |     let ty = cx.tcx.tables().expr_ty(e);
    |                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:1116:31
     |
1116 |         let path_res = cx.tcx.tables().qpath_def(qpath, expr.id);
     |                               ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/loops.rs:1116:31
     |
1116 |         let path_res = cx.tcx.tables().qpath_def(qpath, expr.id);
     |                               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/map_clone.rs:47:59
   |
36 |                         if_let_chain! {[
   |                         - in this macro invocation
...
47 |                                 walk_ptrs_ty_depth(cx.tcx.tables().pat_ty(&first_arg.pat)).1 == 1
   |                                                           ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/map_clone.rs:47:59
   |
36 |                         if_let_chain! {[
   |                         - in this macro invocation
...
47 |                                 walk_ptrs_ty_depth(cx.tcx.tables().pat_ty(&first_arg.pat)).1 == 1
   |                                                           ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/map_clone.rs:104:50
    |
104 |     } else if match_type(cx, walk_ptrs_ty(cx.tcx.tables().expr_ty(arg)), &paths::OPTION) {
    |                                                  ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/map_clone.rs:104:50
    |
104 |     } else if match_type(cx, walk_ptrs_ty(cx.tcx.tables().expr_ty(arg)), &paths::OPTION) {
    |                                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:166:25
    |
166 |         let ty = cx.tcx.tables().expr_ty(ex);
    |                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:166:25
    |
166 |         let ty = cx.tcx.tables().expr_ty(ex);
    |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:257:15
    |
257 |     if cx.tcx.tables().expr_ty(ex).sty == ty::TyBool {
    |               ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:257:15
    |
257 |     if cx.tcx.tables().expr_ty(ex).sty == ty::TyBool {
    |               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:308:34
    |
308 |     if arms.len() >= 2 && cx.tcx.tables().expr_ty(ex).is_integral() {
    |                                  ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/matches.rs:308:34
    |
308 |     if arms.len() >= 2 && cx.tcx.tables().expr_ty(ex).is_integral() {
    |                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mem_forget.rs:34:37
   |
34 |                 let def_id = cx.tcx.tables().qpath_def(qpath, path_expr.id).def_id();
   |                                     ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mem_forget.rs:34:37
   |
34 |                 let def_id = cx.tcx.tables().qpath_def(qpath, path_expr.id).def_id();
   |                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mem_forget.rs:36:44
   |
36 |                     let forgot_ty = cx.tcx.tables().expr_ty(&args[0]);
   |                                            ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mem_forget.rs:36:44
   |
36 |                     let forgot_ty = cx.tcx.tables().expr_ty(&args[0]);
   |                                            ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:606:38
    |
606 |                 let self_ty = cx.tcx.tables().expr_ty_adjusted(&args[0]);
    |                                      ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:606:38
    |
606 |                 let self_ty = cx.tcx.tables().expr_ty_adjusted(&args[0]);
    |                                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:715:41
    |
715 |                     let arg_ty = cx.tcx.tables().expr_ty(arg);
    |                                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:715:41
    |
715 |                     let arg_ty = cx.tcx.tables().expr_ty(arg);
    |                                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:771:30
    |
771 |         let self_ty = cx.tcx.tables().expr_ty(self_expr);
    |                              ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:771:30
    |
771 |         let self_ty = cx.tcx.tables().expr_ty(self_expr);
    |                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:813:21
    |
813 |     let ty = cx.tcx.tables().expr_ty(expr);
    |                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:813:21
    |
813 |     let ty = cx.tcx.tables().expr_ty(expr);
    |                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:838:62
    |
838 |                                if let ty::TyRef(..) = cx.tcx.tables().expr_ty(arg).sty {
    |                                                              ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:838:62
    |
838 |                                if let ty::TyRef(..) = cx.tcx.tables().expr_ty(arg).sty {
    |                                                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:848:25
    |
848 |     let arg_ty = cx.tcx.tables().expr_ty(&args[1]);
    |                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:848:25
    |
848 |     let arg_ty = cx.tcx.tables().expr_ty(&args[1]);
    |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:866:54
    |
866 |         let (self_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(target));
    |                                                      ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:866:54
    |
866 |         let (self_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(target));
    |                                                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:887:49
    |
887 |     let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&args[0]));
    |                                                 ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:887:49
    |
887 |     let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&args[0]));
    |                                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:900:39
    |
896 |     if_let_chain!{[
    |     - in this macro invocation
...
900 |         let Def::Method(did) = cx.tcx.tables().qpath_def(path, fun.id),
    |                                       ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:900:39
    |
896 |     if_let_chain!{[
    |     - in this macro invocation
...
900 |         let Def::Method(did) = cx.tcx.tables().qpath_def(path, fun.id),
    |                                       ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:914:68
    |
914 |     let caller_type = if derefs_to_slice(cx, &iter_args[0], cx.tcx.tables().expr_ty(&iter_args[0])).is_some() {
    |                                                                    ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:914:68
    |
914 |     let caller_type = if derefs_to_slice(cx, &iter_args[0], cx.tcx.tables().expr_ty(&iter_args[0])).is_some() {
    |                                                                    ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:916:37
    |
916 |     } else if match_type(cx, cx.tcx.tables().expr_ty(&iter_args[0]), &paths::VEC) {
    |                                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:916:37
    |
916 |     } else if match_type(cx, cx.tcx.tables().expr_ty(&iter_args[0]), &paths::VEC) {
    |                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:918:37
    |
918 |     } else if match_type(cx, cx.tcx.tables().expr_ty(&iter_args[0]), &paths::VEC_DEQUE) {
    |                                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:918:37
    |
918 |     } else if match_type(cx, cx.tcx.tables().expr_ty(&iter_args[0]), &paths::VEC_DEQUE) {
    |                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:935:26
    |
935 |     let expr_ty = cx.tcx.tables().expr_ty(&get_args[0]);
    |                          ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:935:26
    |
935 |     let expr_ty = cx.tcx.tables().expr_ty(&get_args[0]);
    |                          ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:991:67
    |
991 |         if &*name.node.as_str() == "iter" && may_slice(cx, cx.tcx.tables().expr_ty(&args[0])) {
    |                                                                   ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:991:67
    |
991 |         if &*name.node.as_str() == "iter" && may_slice(cx, cx.tcx.tables().expr_ty(&args[0])) {
    |                                                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1014:49
     |
1014 |     let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&unwrap_args[0]));
     |                                                 ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1014:49
     |
1014 |     let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&unwrap_args[0]));
     |                                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1039:30
     |
1039 |     if match_type(cx, cx.tcx.tables().expr_ty(&ok_args[0]), &paths::RESULT) {
     |                              ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1039:30
     |
1039 |     if match_type(cx, cx.tcx.tables().expr_ty(&ok_args[0]), &paths::RESULT) {
     |                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1040:34
     |
1040 |         let result_type = cx.tcx.tables().expr_ty(&ok_args[0]);
     |                                  ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1040:34
     |
1040 |         let result_type = cx.tcx.tables().expr_ty(&ok_args[0]);
     |                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1055:30
     |
1055 |     if match_type(cx, cx.tcx.tables().expr_ty(&map_args[0]), &paths::OPTION) {
     |                              ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1055:30
     |
1055 |     if match_type(cx, cx.tcx.tables().expr_ty(&map_args[0]), &paths::OPTION) {
     |                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1084:30
     |
1084 |     if match_type(cx, cx.tcx.tables().expr_ty(&map_args[0]), &paths::OPTION) {
     |                              ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1084:30
     |
1084 |     if match_type(cx, cx.tcx.tables().expr_ty(&map_args[0]), &paths::OPTION) {
     |                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1211:43
     |
1203 |     if_let_chain! {[
     |     - in this macro invocation
...
1211 |         let self_ty = walk_ptrs_ty(cx.tcx.tables().expr_ty_adjusted(&args[0][0]));
     |                                           ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/methods.rs:1211:43
     |
1203 |     if_let_chain! {[
     |     - in this macro invocation
...
1211 |         let self_ty = walk_ptrs_ty(cx.tcx.tables().expr_ty_adjusted(&args[0][0]));
     |                                           ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/minmax.rs:65:33
   |
65 |             let def_id = cx.tcx.tables().qpath_def(qpath, path.id).def_id();
   |                                 ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/minmax.rs:65:33
   |
65 |             let def_id = cx.tcx.tables().qpath_def(qpath, path.id).def_id();
   |                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:315:49
    |
315 |                     non_macro_local(cx, &cx.tcx.tables().qpath_def(qpath, expr.id)) {
    |                                                 ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:315:49
    |
315 |                     non_macro_local(cx, &cx.tcx.tables().qpath_def(qpath, expr.id)) {
    |                                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:392:34
    |
392 |     matches!(walk_ptrs_ty(cx.tcx.tables().expr_ty(expr)).sty, ty::TyFloat(_))
    |                                  ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:392:34
    |
392 |     matches!(walk_ptrs_ty(cx.tcx.tables().expr_ty(expr)).sty, ty::TyFloat(_))
    |                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:400:25
    |
400 |                 (cx.tcx.tables().expr_ty(&args[0]), snippet(cx, args[0].span, ".."))
    |                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:400:25
    |
400 |                 (cx.tcx.tables().expr_ty(&args[0]), snippet(cx, args[0].span, ".."))
    |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:408:29
    |
408 |                     (cx.tcx.tables().expr_ty(&v[0]), snippet(cx, v[0].span, ".."))
    |                             ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:408:29
    |
408 |                     (cx.tcx.tables().expr_ty(&v[0]), snippet(cx, v[0].span, ".."))
    |                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:419:27
    |
419 |     let other_ty = cx.tcx.tables().expr_ty(other);
    |                           ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:419:27
    |
419 |     let other_ty = cx.tcx.tables().expr_ty(other);
    |                           ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:452:53
    |
452 |     args.len() == 1 && matches!(walk_ptrs_ty(cx.tcx.tables().expr_ty(&args[0])).sty, ty::TyStr)
    |                                                     ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/misc.rs:452:53
    |
452 |     args.len() == 1 && matches!(walk_ptrs_ty(cx.tcx.tables().expr_ty(&args[0])).sty, ty::TyStr)
    |                                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mut_mut.rs:71:93
   |
71 |             } else if let TyRef(_, TypeAndMut { mutbl: hir::MutMutable, .. }) = self.cx.tcx.tables().expr_ty(e).sty {
   |                                                                                             ^^^^^^
   |
note: did you mean to write `self.cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mut_mut.rs:71:93
   |
71 |             } else if let TyRef(_, TypeAndMut { mutbl: hir::MutMutable, .. }) = self.cx.tcx.tables().expr_ty(e).sty {
   |                                                                                             ^^^^^^

error: no field `node_types` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mut_reference.rs:40:52
   |
40 |                 let function_type = borrowed_table.node_types
   |                                                    ^^^^^^^^^^ unknown field

error: no field `method_map` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mut_reference.rs:53:50
   |
53 |                 let method_type = borrowed_table.method_map.get(&method_call).expect("This should never happen.");
   |                                                  ^^^^^^^^^^ unknown field

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mutex_atomic.rs:59:25
   |
59 |         let ty = cx.tcx.tables().expr_ty(expr);
   |                         ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/mutex_atomic.rs:59:25
   |
59 |         let ty = cx.tcx.tables().expr_ty(expr);
   |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_borrow.rs:43:43
   |
43 |             if let ty::TyRef(..) = cx.tcx.tables().expr_ty(inner).sty {
   |                                           ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_borrow.rs:43:43
   |
43 |             if let ty::TyRef(..) = cx.tcx.tables().expr_ty(inner).sty {
   |                                           ^^^^^^

error: no field `adjustments` on type `core::cell::Ref<'_, rustc::dep_graph::DepTrackingMap<rustc::ty::maps::Tables<'_>>>`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_borrow.rs:45:44
   |
45 |                     cx.tcx.tables.borrow().adjustments.get(&e.id).map(|a| &a.kind) {
   |                                            ^^^^^^^^^^^ unknown field

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_borrow.rs:63:48
   |
61 |         if_let_chain! {[
   |         - in this macro invocation
62 |             let PatKind::Binding(BindingMode::BindByRef(MutImmutable), _, _, _) = pat.node,
63 |             let ty::TyRef(_, ref tam) = cx.tcx.tables().pat_ty(pat).sty,
   |                                                ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_borrow.rs:63:48
   |
61 |         if_let_chain! {[
   |         - in this macro invocation
62 |             let PatKind::Binding(BindingMode::BindByRef(MutImmutable), _, _, _) = pat.node,
63 |             let ty::TyRef(_, ref tam) = cx.tcx.tables().pat_ty(pat).sty,
   |                                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_update.rs:36:29
   |
36 |             let ty = cx.tcx.tables().expr_ty(expr);
   |                             ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/needless_update.rs:36:29
   |
36 |             let ty = cx.tcx.tables().expr_ty(expr);
   |                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/neg_multiply.rs:53:16
   |
48 |     if_let_chain!([
   |     - in this macro invocation
...
53 |         cx.tcx.tables().expr_ty(exp).is_integral()
   |                ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/neg_multiply.rs:53:16
   |
48 |     if_let_chain!([
   |     - in this macro invocation
...
53 |         cx.tcx.tables().expr_ty(exp).is_integral()
   |                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/no_effect.rs:72:34
   |
72 |                 let def = cx.tcx.tables().qpath_def(qpath, callee.id);
   |                                  ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/no_effect.rs:72:34
   |
72 |                 let def = cx.tcx.tables().qpath_def(qpath, callee.id);
   |                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/no_effect.rs:156:34
    |
156 |                 let def = cx.tcx.tables().qpath_def(qpath, callee.id);
    |                                  ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/no_effect.rs:156:34
    |
156 |                 let def = cx.tcx.tables().qpath_def(qpath, callee.id);
    |                                  ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/ok_if_let.rs:53:56
   |
45 |         if_let_chain! {[ //begin checking variables
   |         - in this macro invocation
...
53 |             let is_result_type = match_type(cx, cx.tcx.tables().expr_ty(&result_types[0]), &paths::RESULT);
   |                                                        ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/ok_if_let.rs:53:56
   |
45 |         if_let_chain! {[ //begin checking variables
   |         - in this macro invocation
...
53 |             let is_result_type = match_type(cx, cx.tcx.tables().expr_ty(&result_types[0]), &paths::RESULT);
   |                                                        ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/open_options.rs:38:57
   |
38 |             let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&arguments[0]));
   |                                                         ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/open_options.rs:38:57
   |
38 |             let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&arguments[0]));
   |                                                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/open_options.rs:66:53
   |
66 |         let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&arguments[0]));
   |                                                     ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/open_options.rs:66:53
   |
66 |         let (obj_ty, _) = walk_ptrs_ty_depth(cx.tcx.tables().expr_ty(&arguments[0]));
   |                                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:42:20
   |
35 |         if_let_chain! {[
   |         - in this macro invocation
...
42 |             cx.tcx.tables().expr_ty(ident1).is_integral(),
   |                    ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:42:20
   |
35 |         if_let_chain! {[
   |         - in this macro invocation
...
42 |             cx.tcx.tables().expr_ty(ident1).is_integral(),
   |                    ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:43:20
   |
35 |         if_let_chain! {[
   |         - in this macro invocation
...
43 |             cx.tcx.tables().expr_ty(ident2).is_integral()
   |                    ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:43:20
   |
35 |         if_let_chain! {[
   |         - in this macro invocation
...
43 |             cx.tcx.tables().expr_ty(ident2).is_integral()
   |                    ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:66:20
   |
59 |         if_let_chain! {[
   |         - in this macro invocation
...
66 |             cx.tcx.tables().expr_ty(ident1).is_integral(),
   |                    ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:66:20
   |
59 |         if_let_chain! {[
   |         - in this macro invocation
...
66 |             cx.tcx.tables().expr_ty(ident1).is_integral(),
   |                    ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:67:20
   |
59 |         if_let_chain! {[
   |         - in this macro invocation
...
67 |             cx.tcx.tables().expr_ty(ident2).is_integral()
   |                    ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/overflow_check_conditional.rs:67:20
   |
59 |         if_let_chain! {[
   |         - in this macro invocation
...
67 |             cx.tcx.tables().expr_ty(ident2).is_integral()
   |                    ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/print.rs:124:41
    |
70  |         if_let_chain! {[
    |         - in this macro invocation
...
124 |                     let def_id = cx.tcx.tables().qpath_def(qpath, args[1].id).def_id();
    |                                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/print.rs:124:41
    |
70  |         if_let_chain! {[
    |         - in this macro invocation
...
124 |                     let def_id = cx.tcx.tables().qpath_def(qpath, args[1].id).def_id();
    |                                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/ranges.rs:93:21
   |
93 |     let ty = cx.tcx.tables().expr_ty(expr);
   |                     ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/ranges.rs:93:21
   |
93 |     let ty = cx.tcx.tables().expr_ty(expr);
   |                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/regex.rs:94:35
    |
91  |         if_let_chain!{[
    |         - in this macro invocation
...
94  |             match_type(cx, cx.tcx.tables().expr_ty(expr), &paths::REGEX),
    |                                   ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/regex.rs:94:35
    |
91  |         if_let_chain!{[
    |         - in this macro invocation
...
94  |             match_type(cx, cx.tcx.tables().expr_ty(expr), &paths::REGEX),
    |                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/regex.rs:121:33
    |
116 |         if_let_chain!{[
    |         - in this macro invocation
...
121 |             let def_id = cx.tcx.tables().qpath_def(qpath, fun.id).def_id();
    |                                 ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/regex.rs:121:33
    |
116 |         if_let_chain!{[
    |         - in this macro invocation
...
121 |             let def_id = cx.tcx.tables().qpath_def(qpath, fun.id).def_id();
    |                                 ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/shadow.rs:146:25
    |
146 |     let var_ty = cx.tcx.tables().node_id_to_type(pat_id);
    |                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/shadow.rs:146:25
    |
146 |     let var_ty = cx.tcx.tables().node_id_to_type(pat_id);
    |                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/strings.rs:117:40
    |
117 |     match_type(cx, walk_ptrs_ty(cx.tcx.tables().expr_ty(e)), &paths::STRING)
    |                                        ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/strings.rs:117:40
    |
117 |     match_type(cx, walk_ptrs_ty(cx.tcx.tables().expr_ty(e)), &paths::STRING)
    |                                        ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:91:37
   |
91 |                 let def_id = cx.tcx.tables().qpath_def(qpath, path_expr.id).def_id();
   |                                     ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:91:37
   |
91 |                 let def_id = cx.tcx.tables().qpath_def(qpath, path_expr.id).def_id();
   |                                     ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:94:42
   |
94 |                     let from_ty = cx.tcx.tables().expr_ty(&args[0]);
   |                                          ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:94:42
   |
94 |                     let from_ty = cx.tcx.tables().expr_ty(&args[0]);
   |                                          ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:95:40
   |
95 |                     let to_ty = cx.tcx.tables().expr_ty(e);
   |                                        ^^^^^^
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/transmute.rs:95:40
   |
95 |                     let to_ty = cx.tcx.tables().expr_ty(e);
   |                                        ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:114:30
    |
114 |             let def = cx.tcx.tables().qpath_def(qpath, ast_ty.id);
    |                              ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:114:30
    |
114 |             let def = cx.tcx.tables().qpath_def(qpath, ast_ty.id);
    |                              ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:122:59
    |
118 |                     if_let_chain! {[
    |                     - in this macro invocation
...
122 |                         let def::Def::Struct(..) = cx.tcx.tables().qpath_def(qpath, vec.id),
    |                                                           ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:122:59
    |
118 |                     if_let_chain! {[
    |                     - in this macro invocation
...
122 |                         let def::Def::Struct(..) = cx.tcx.tables().qpath_def(qpath, vec.id),
    |                                                           ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:123:59
    |
118 |                     if_let_chain! {[
    |                     - in this macro invocation
...
123 |                         let Some(did) = opt_def_id(cx.tcx.tables().qpath_def(qpath, vec.id)),
    |                                                           ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:123:59
    |
118 |                     if_let_chain! {[
    |                     - in this macro invocation
...
123 |                         let Some(did) = opt_def_id(cx.tcx.tables().qpath_def(qpath, vec.id)),
    |                                                           ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:198:32
    |
198 |         let bindtype = &cx.tcx.tables().pat_ty(&local.pat).sty;
    |                                ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:198:32
    |
198 |         let bindtype = &cx.tcx.tables().pat_ty(&local.pat).sty;
    |                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:269:35
    |
269 |                 let sty = &cx.tcx.tables().expr_ty(left).sty;
    |                                   ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:269:35
    |
269 |                 let sty = &cx.tcx.tables().expr_ty(left).sty;
    |                                   ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:513:48
    |
513 |             let (cast_from, cast_to) = (cx.tcx.tables().expr_ty(ex), cx.tcx.tables().expr_ty(expr));
    |                                                ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:513:48
    |
513 |             let (cast_from, cast_to) = (cx.tcx.tables().expr_ty(ex), cx.tcx.tables().expr_ty(expr));
    |                                                ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:513:77
    |
513 |             let (cast_from, cast_to) = (cx.tcx.tables().expr_ty(ex), cx.tcx.tables().expr_ty(expr));
    |                                                                             ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:513:77
    |
513 |             let (cast_from, cast_to) = (cx.tcx.tables().expr_ty(ex), cx.tcx.tables().expr_ty(expr));
    |                                                                             ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:757:57
    |
757 |                     if ty::TyUint(UintTy::U8) == cx.tcx.tables().expr_ty(expr).sty && !in_macro(cx, expr.span) {
    |                                                         ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:757:57
    |
757 |                     if ty::TyUint(UintTy::U8) == cx.tcx.tables().expr_ty(expr).sty && !in_macro(cx, expr.span) {
    |                                                         ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:830:15
    |
830 |     if cx.tcx.tables().expr_ty(lhs) != cx.tcx.tables().expr_ty(rhs) {
    |               ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:830:15
    |
830 |     if cx.tcx.tables().expr_ty(lhs) != cx.tcx.tables().expr_ty(rhs) {
    |               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:830:47
    |
830 |     if cx.tcx.tables().expr_ty(lhs) != cx.tcx.tables().expr_ty(rhs) {
    |                                               ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:830:47
    |
830 |     if cx.tcx.tables().expr_ty(lhs) != cx.tcx.tables().expr_ty(rhs) {
    |                                               ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:872:22
    |
872 |     let ty = &cx.tcx.tables().expr_ty(expr).sty;
    |                      ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:872:22
    |
872 |     let ty = &cx.tcx.tables().expr_ty(expr).sty;
    |                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:1038:22
     |
1038 |         match cx.tcx.tables().expr_ty(cast_exp).sty {
     |                      ^^^^^^
     |
note: did you mean to write `cx.tcx.tables`?
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/types.rs:1038:22
     |
1038 |         match cx.tcx.tables().expr_ty(cast_exp).sty {
     |                      ^^^^^^

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/vec.rs:39:61
   |
38 |           if_let_chain!{[
   |  _________- starting here...
39 | |             let ty::TypeVariants::TyRef(_, ref ty) = cx.tcx.tables().expr_ty_adjusted(expr).sty,
   | |                                                             ^^^^^^
40 | |             let ty::TypeVariants::TySlice(..) = ty.ty.sty,
41 | |             let ExprAddrOf(_, ref addressee) = expr.node,
42 | |             let Some(vec_args) = higher::vec_macro(cx, addressee),
43 | |         ], {
44 | |             check_vec_macro(cx, &vec_args, expr.span);
45 | |         }}
   | |__________- ...ending here: in this macro invocation
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/vec.rs:39:61
   |
38 |           if_let_chain!{[
   |  _________- starting here...
39 | |             let ty::TypeVariants::TyRef(_, ref ty) = cx.tcx.tables().expr_ty_adjusted(expr).sty,
   | |                                                             ^^^^^^
40 | |             let ty::TypeVariants::TySlice(..) = ty.ty.sty,
41 | |             let ExprAddrOf(_, ref addressee) = expr.node,
42 | |             let Some(vec_args) = higher::vec_macro(cx, addressee),
43 | |         ], {
44 | |             check_vec_macro(cx, &vec_args, expr.span);
45 | |         }}
   | |__________- ...ending here: in this macro invocation

error: no method named `tables` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/vec.rs:51:41
   |
48 |           if_let_chain!{[
   |  _________- starting here...
49 | |             let Some((_, arg, _)) = higher::for_loop(expr),
50 | |             let Some(vec_args) = higher::vec_macro(cx, arg),
51 | |             is_copy(cx, vec_type(cx.tcx.tables().expr_ty_adjusted(arg)), cx.tcx.map.get_parent(expr.id)),
   | |                                         ^^^^^^
52 | |         ], {
53 | |             // report the error around the `vec!` not inside `<std macros>:`
54 | |             let span = cx.sess().codemap().source_callsite(arg.span);
55 | |             check_vec_macro(cx, &vec_args, span);
56 | |         }}
   | |__________- ...ending here: in this macro invocation
   |
note: did you mean to write `cx.tcx.tables`?
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/vec.rs:51:41
   |
48 |           if_let_chain!{[
   |  _________- starting here...
49 | |             let Some((_, arg, _)) = higher::for_loop(expr),
50 | |             let Some(vec_args) = higher::vec_macro(cx, arg),
51 | |             is_copy(cx, vec_type(cx.tcx.tables().expr_ty_adjusted(arg)), cx.tcx.map.get_parent(expr.id)),
   | |                                         ^^^^^^
52 | |         ], {
53 | |             // report the error around the `vec!` not inside `<std macros>:`
54 | |             let span = cx.sess().codemap().source_callsite(arg.span);
55 | |             check_vec_macro(cx, &vec_args, span);
56 | |         }}
   | |__________- ...ending here: in this macro invocation

error: no method named `tables` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/swap.rs:92:58
    |
63  |         if_let_chain!{[
    |         - in this macro invocation
...
92  |                             let ty = walk_ptrs_ty(cx.tcx.tables().expr_ty(lhs1));
    |                                                          ^^^^^^
    |
note: did you mean to write `cx.tcx.tables`?
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.107/src/swap.rs:92:58
    |
63  |         if_let_chain!{[
    |         - in this macro invocation
...
92  |                             let ty = walk_ptrs_ty(cx.tcx.tables().expr_ty(lhs1));
    |                                                          ^^^^^^

error: aborting due to 128 previous errors

error: failed to compile `clippy v0.0.107`, intermediate artifacts can be found at `/tmp/cargo-install.moeQKtYvfmTy`

Caused by:
  Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
```

</details>

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #1440

### CODE REVIEW

File: clippy_lints/src/booleans.rs [hunk 1]
```diff
@@ -404,6 +412,6 @@ impl<'a, 'tcx> Visitor<'tcx> for NonminimalBoolVisitor<'a, 'tcx> {
         }
     }
     fn nested_visit_map<'this>(&'this mut self) -> NestedVisitorMap<'this, 'tcx> {
-        NestedVisitorMap::All(&self.cx.tcx.map)
+        NestedVisitorMap::None
```
Comment (oli-obk) [inline clippy_lints/src/booleans.rs]: Because it never made sense to begin with. We'd be running the lint twice, once through the visitor and once through the LateLintPass

File: tests/compile-fail/cyclomatic_complexity.rs [hunk 2]
```diff
@@ -146,7 +146,7 @@ fn lots_of_short_circuits2() -> bool { //~ ERROR: the function has a cyclomatic
 
 #[cyclomatic_complexity = "0"]
 fn baa() { //~ ERROR: the function has a cyclomatic complexity of 2
-    let x = || match 99 {
+    let x = || match 99 { //~ ERROR: the function has a cyclomatic complexity of 2
```
Comment (oli-obk) [inline tests/compile-fail/cyclomatic_complexity.rs]: No, actually we are now also linting closures

File: clippy_lints/src/booleans.rs (hunk 1 above)
Comment (oli-obk) [inline clippy_lints/src/booleans.rs]: Because it never made sense to begin with. We'd be running the lint twice, once through the visitor and once through the LateLintPass

**Comment by oli-obk** [comment]
Travis likes it now. I won't be able to publish today.

**Comment by mcarton** [comment]
I'll do it now.

**Comment by oli-obk** [comment]
Thx
