### PR TITLE
Lint on `Err(_)` arm of a match

### LINKED ISSUE #1270: Lint idea: `Err(_)`
This is the 3rd scenario found by [this paper](https://blog.acolyer.org/2016/10/06/simple-testing-can-prevent-most-critical-failures/) that commonly causes critical failures: "Error handlers that catch an abstract exception type (e.g. Exception or Throwable in Java) and then take drastic action such as aborting the system."

Now, I don't know if this directly translates. And I think the result_unwrap_used and option_unwrap_used lints catch the most common ways of doing this in Rust! But there's another way, and I don't know if this is common enough to justify a lint:

``` rust
match something {
    Ok(stuff) => { 
        // happy path stuff
    },
    Err(_) => {
        panic!("stop the world");
    },
}    
```

the key parts being the matching of any type of error, and the drastic action in the `Err` arm.

Again, please do close this if this doesn't seem like a worthwhile idea!! <3

### PR DESCRIPTION
**Pull request by bood**
Fix #1270

### CODE REVIEW

File: clippy_lints/src/matches.rs [hunk 1]
```diff
@@ -121,6 +121,26 @@ declare_lint! {
     "a match with overlapping arms"
 }
 
+/// **What it does:** Checks for arm matches all errors with `Err(_)`.
```
Comment (oli-obk) [inline clippy_lints/src/matches.rs]: I think this needs a `which` between `arm` and `matches`

File: clippy_lints/src/matches.rs [hunk 2]
```diff
@@ -121,6 +121,26 @@ declare_lint! {
...
+///
+/// **Why is this bad?** It is a bad practice to catch all errors the same way
```
Comment (oli-obk) [inline clippy_lints/src/matches.rs]: ... and take drastic actions like `panic!`

File: clippy_lints/src/matches.rs [hunk 3]
```diff
@@ -121,6 +121,26 @@ declare_lint! {
...
+///
+/// **Known problems:** None.
+///
+/// **Example:**
+/// ```rust
+/// let x : Result(i32, &str) = Ok(3);
+/// match x {
+///     Ok(_) => println!("ok"),
+///     Err(_) => println!("err"),
```
Comment (oli-obk) [inline clippy_lints/src/matches.rs]: The way the issue was written, this should be legal, only `panic!("err")` should be illegal.

File: clippy_lints/src/matches.rs [hunk 4]
```diff
@@ -322,6 +344,45 @@ fn check_overlapping_arms(cx: &LateContext, ex: &Expr, arms: &[Arm]) {
...
+        for arm in arms {
+            if let PatKind::TupleStruct(ref path, ref inner, _) = arm.pats[0].node {
+                let path_str = print::to_string(print::NO_ANN, |s| s.print_qpath(path, false));
+                if inner.iter().any(|pat| pat.node == PatKind::Wild) &&
+                    path_str == "Err" {
+                        // `Err(_)` arm found
+                        let mut need_lint = true;
+                        if let ExprBlock(ref block) = arm.body.node {
+                            if is_unreachable_block(cx, block) {
+                                need_lint = false;
```
Comment (oli-obk) [inline clippy_lints/src/matches.rs]: Please use the `if_let_chain` macro to reduce rightward drift instead of mutable bools.

**Comment by oli-obk** [comment]
Also, please run `cargo fmt` in the `clippy_lints` directory.

File: clippy_lints/src/matches.rs (hunk 3 above)
Comment (bood) [inline clippy_lints/src/matches.rs]: Ah...then I misunderstood. So it's only illegal when `panic` is in the block?

Comment (oli-obk) [inline clippy_lints/src/matches.rs]: yes, we might extend it to more things later, but for now, just if there's a `panic!` (could probably generalize it to anything of type `!`, not sure how far that is propagated yet.)

**Comment by bood** [comment]
Updated. Only `panic!` triggers the lint now.

File: clippy_lints/src/matches.rs [hunk 5]
```diff
@@ -322,6 +347,45 @@ fn check_overlapping_arms(cx: &LateContext, ex: &Expr, arms: &[Arm]) {
...
+    }
+}
+
+// If the block contains only a `panic!` macro (as expression or statement)
+fn is_panic_block(cx: &LateContext, block: &Block) -> bool {
+    match (&block.expr, block.stmts.len(), block.stmts.first()) {
+        (&Some(ref exp), 0, _) => {
+            is_expn_of(cx, exp.span, "panic").is_some() && is_expn_of(cx, exp.span, "unreachable").is_none()
+        },
+        (&None, 1, Some(ref stmt)) => {
```
Comment (oli-obk) [inline clippy_lints/src/matches.rs]: the `ref` is unnecessary here.

Comment (bood) [inline clippy_lints/src/matches.rs]: It's not compiling without the first `ref` in `ref exp`, but the second in `ref stmt` can be removed.

```
error[E0507]: cannot move out of borrowed content
   --> clippy_lints/src/matches.rs:379:10
    |
379 |         (&Some(exp), 0, _) => {
    |          ^^^^^^---^
    |          |     |
    |          |     hint: to prevent move, use `ref exp` or `ref mut exp`
    |          cannot move out of borrowed content
```

**Comment by bood** [comment]
Unnecessary `ref` removed.

**Comment by oli-obk** [comment]
thanks!
