### PR TITLE
Don't assume the first package in the result of `cargo metadata` is the current crate.

### LINKED ISSUE #1247: No library targets found when using workspaces
I have a project that is using cargo's workspaces where the root is a bin crate. Running `cargo clippy` in the root folder causes `error: no library targets found`.

This seems to be because `cargo metadata --no-deps` lists every crate in the workspace e.g.

```json
{  
   "packages":[  
      {  
         "name":"gl32",
         "version":"0.0.1",
         "id":"gl32 0.0.1 (path+file:///project/location/gl32)",
         "license":null,
         "license_file":null,
         "source":null,
         "dependencies":[  ],
         "targets":[  
            {  
               "kind":[  
                  "lib"
               ],
               "name":"gl32",
               "src_path":"/project/location/./gl32/src/lib.rs"
            },
            {  
               "kind":[  
                  "custom-build"
               ],
               "name":"build-script-build",
               "src_path":"build.rs"
            }
         ],
         "features":{  

         },
         "manifest_path":"/project/location/./gl32/Cargo.toml"
      },
// <snip other sub-crates>
      {  
         "name":"game",
         "version":"0.1.0",
         "id":"game 0.1.0 (path+file:///project/location)",
         "license":null,
         "license_file":null,
         "source":null,
         "dependencies":[  ],
         "targets":[  
            {  
               "kind":[  
                  "bin"
               ],
               "name":"game",
               "src_path":"/project/location/src/main.rs"
            }
         ],
         "features":{  
            "profile":[  

            ],
            "default":[  
               "profile"
            ]
         },
         "manifest_path":"/project/location/Cargo.toml"
      }
   ],
///etc 
```

And since the first one is a library crate it ends up invoking rustc with `--lib` instead of `--bin`. I'm not sure how this can be worked around.

### PR DESCRIPTION
**Pull request by Arnavion**
Instead find the one with the manifest path that matches the --manifest-path argument or the current directory.

Fixes #1247

---

This contains one breaking API change in the signature of `clippy_lints::utils::cargo::metadata()`. I could revert it and `clone()` the option in `clippy` if you don't want the breaking change.

---

I can't just define `Package::manifest_path` as a `PathBuf` instead of a `String` because [this](https://github.com/rust-lang-nursery/rustc-serialize/blob/740f705/src/serialize.rs#L1356) leads to `Json(ExpectedError("Array", "\"C:\\\\foo\\\\bar\\\\Cargo.toml\""))`

### CODE REVIEW

File: clippy_lints/src/utils/cargo.rs [hunk 1]
```diff
@@ -65,10 +65,10 @@ impl From<json::DecoderError> for Error {
     }
 }
 
-pub fn metadata(manifest_path: Option<String>) -> Result<Metadata, Error> {
+pub fn metadata(manifest_path_arg: &Option<String>) -> Result<Metadata, Error> {
```
Comment (oli-obk) [inline clippy_lints/src/utils/cargo.rs]: We don't have a lint that tells us to use Option<&str> instead? We should make one

File: src/main.rs [hunk 2]
```diff
@@ -138,10 +138,30 @@ pub fn main() {
...
+        let package_index = metadata.packages.iter()
+            .position(|package| {
+                let package_manifest_path = Path::new(&package.manifest_path);
+                if let Some(ref manifest_path) = manifest_path {
+                    package_manifest_path == manifest_path
+                } else if let Ok(ref current_dir) = current_dir {
+                    let package_manifest_directory = package_manifest_path.parent().expect("could not find parent directory of package manifest");
+                    package_manifest_directory == current_dir
+                } else {
+                    panic!("could not read current directory")
```
Comment (oli-obk) [inline src/main.rs]: Use expect on current_dir on the above if let

File: clippy_lints/src/utils/cargo.rs (hunk 1 above)
Comment (mcarton) [inline clippy_lints/src/utils/cargo.rs]: :+1: but IMO, this should be an improvement of `ptr_arg`, not a new lint.

**Comment by oli-obk** [comment]
Lgtm after two nits

**Comment by oli-obk** [comment]
superb! thanks
