### PR TITLE
Small fixes

### LINKED ISSUE #1075: suggest the | for match_same_arms
I ran into `match_same_arms` and was quite confused.  I got ready to report a false positive, but then I found #860 and figured out that I just needed to use `|` in my pattern. 

In #860 in the comments having clippy suggest of `|` is mentioned, but no issue seems to have been opened. So I'm doing so now :)

### PR DESCRIPTION
**Pull request by mcarton**
Fix #1075.
Fix point 2 of [`rustfix`'s Gotchas](https://github.com/killercup/rustfix/blob/dd49d9f71e8a419490c70b9c55cc40d133004573/Readme.md#gotchas).
Fix another issue I can't find the #id of.

### CODE REVIEW

File: clippy_lints/src/new_without_default.rs [hunk 1]
```diff
@@ -118,20 +118,26 @@ impl LateLintPass for NewWithoutDefault {
...
-                                               db.span_suggestion(span,
-                                                                  "try this",
-                                                                  format!("impl Default for {} {{ fn default() -> \
-                                                                          Self {{ {}::new() }} }}", self_ty, self_ty));
-                                           });
+                        db.suggest_prepend_item(cx,
+                                                  span,
+                                                  "try this",
+                                                  &format!(
+"impl Default for {} {{
```
Comment (Manishearth) [inline clippy_lints/src/new_without_default.rs]: IIRC you can indent strings and it works. But this is okay too.

Comment (mcarton) [inline clippy_lints/src/new_without_default.rs]: If you indent the string, all of the indentation is included except if you use `\` and then none of the indentation is included:

```rust
    "
    foo
    bar
        baz" == "\n    foo\n    bar\n        baz";

"\
foo\
    bar\
        baz" == "foobarbaz"
```
