### PR TITLE
Fix wrong suggestion in `WHILE_LET_LOOP`

### LINKED ISSUE #675: Wrong suggestion with `while_let_loop`
Encountered something like that [in the wild](https://github.com/murarth/ketos/pull/8):
```rust
    loop {
        let (e, l) = match s.split_whitespace().next() {
            Some(word) => (word.is_empty(), word.len()),
            None => break
        };

        let _ = (e, l);
    }
```
produces:
```rust
foo.rs:46:5: 53:6 error: this loop could be written as a `while let` loop
foo.rs:46     loop {
foo.rs:47         let (e, l) = match s.split_whitespace().next() {
foo.rs:48             Some(word) => (word.is_empty(), word.len()),
foo.rs:49             None => break
foo.rs:50         };
foo.rs:51 
          ...
foo.rs:4:9: 4:23 note: lint level defined here
foo.rs:4 #![deny(while_let_loop)]
                 ^~~~~~~~~~~~~~
foo.rs:46:5: 53:6 help: try
while let Some(word) = s.split_whitespace().next() {
    let _ = (e, l);
}
```

### PR DESCRIPTION
**Pull request by mcarton**
Ok, I lied in the title. This basically *removes* the problematic part but:

1. it was ugly with big bodies;
2. it was not indented properly;
3. it wasn’t very smart (fix #675).

And the « // FIXME: should probably be an ellipsis » comment I removed suggests I’m not as lazy as this fix looks :smile:.

### CODE REVIEW

File: src/loops.rs [hunk 1]
```diff
@@ -264,22 +250,20 @@ impl LateLintPass for LoopsPass {
...
+                                // 1) it was ugly with big bodies;
+                                // 2) it was not indented properly;
+                                // 3) it wasn’t very smart (see #675).
                                 span_lint_and_then(cx,
                                                    WHILE_LET_LOOP,
                                                    expr.span,
                                                    "this loop could be written as a `while let` loop",
                                                    |db| {
-                                                       let sug = format!("while let {} = {} {}",
+                                                       let sug = format!("while let {} = {} {{ ... }}",
```
Comment (llogiq) [inline src/loops.rs]: Microscopical nit: we customarily use `..` to denote multiple statements (or fields).

**Comment by llogiq** [comment]
Thanks!
