### PR TITLE
split wrong_self_convention in pub/default visibility part

### LINKED ISSUE #282: wrong_self_convention vs. back-compat
If one runs clippy against stable code, the `wrong_self_convention` lint suggests a rename. This should not be taken lightly, for it can break backwards-compatibility.

I have added some text to that effect to the wiki. Perhaps the lint message should give at least a hint to be careful.

### PR DESCRIPTION
**Pull request by llogiq**
This closes #282

### CODE REVIEW

**Comment by llogiq** [comment]
@birkenfeld r?

File: src/methods.rs [hunk 1]
```diff
@@ -93,7 +96,12 @@ impl LintPass for MethodsPass {
                     for &(prefix, self_kinds) in &CONVENTIONS {
                         if name.as_str().starts_with(prefix) &&
                                 !self_kinds.iter().any(|k| k.matches(&sig.explicit_self.node, is_copy)) {
-                            span_lint(cx, WRONG_SELF_CONVENTION, sig.explicit_self.span, &format!(
+                            let lint = if let Visibility::Public = item.vis {
```
Comment (birkenfeld) [inline src/methods.rs]: Nit: doesn't need an `if let`.
