### PR TITLE
Search for `clippy.toml` recursively

### LINKED ISSUE #909: clippy.toml is not taken into account if running `cargo build` from a subdirectory
## Steps to reproduce
1. `git clone https://github.com/JohanLorenzo/clippy-toml-bug.git`
2. `cd clippy-toml-bug/foo` . Please note we're in the subdirectory "foo"
3. `cargo build` => Build fails because `MyIdent` is not between ticks
4. `cd .. && cargo build` => Build passes, because `MyIdent` is [whitelisted in clippy.toml](https://github.com/JohanLorenzo/clippy-toml-bug/blob/master/clippy.toml)
## Potential cause

I'm not too sure. It seems clippy.toml is [not prefixed with the project path](https://github.com/Manishearth/rust-clippy/blob/855b292cda017fe47674725b2866ba760fed1f67/src/lib.rs#L275). What do you all think?

### LINKED ISSUE #1294: if no `clippy.toml` is available, go up the directory tree until one is found
cargo does the same for `Cargo.toml` and `.cargo` directories. This would allow users to enforce their clippy rules across directories

### PR DESCRIPTION
**Pull request by mcarton**
Also search for `.clippy.toml` for consistency with *rustfmt*.

Fix  #909.
Fix #1294.
Does not fix  #1293, because we get:

> ```
thread 'main' panicked at 'could not find matching package'
```

@oli-obk: has `cargo clippy` ever worked outside the root of the project (independently of `cargo.toml`)?

### CODE REVIEW

**Comment by oli-obk** [comment]
Nope it never worked if called from a subdir

File: clippy_lints/src/utils/conf.rs [hunk 1]
```diff
@@ -179,13 +178,51 @@ define_Conf! {
...
+
+    let mut current = try!(env::current_dir());
+
+    loop {
+        for config_file_name in &CONFIG_FILE_NAMES {
+            let config_file = current.join(config_file_name);
+            match fs::metadata(&config_file) {
+                // Only return if it's a file to handle the unlikely situation of a directory named
+                // `clippy.toml`.
+                Ok(ref md) if md.is_file() => return Ok(Some(config_file)),
```
Comment (oli-obk) [inline clippy_lints/src/utils/conf.rs]: Doesn't this also exclude symlinks?
