### PR TITLE
spelling fix, rework needless_bool with snippet (fixes #150)

### LINKED ISSUE #150: needless_bool can have a clearer error message
The middle two error messages [here](https://github.com/Manishearth/rust-clippy/blob/master/src/needless_bool.rs#L33) talk of a "predicate", but it would be better if we show the user what can be done.

E.g. change "your" to "this", and then add a span_help which says "Consider replacing this if-else with `{operator}{snippet}`", where `snippet` is the `utils::snippet()` of the predicate, and `operator` is `!` or nothing, given the type of if.

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

File: src/needless_bool.rs [hunk 1]
```diff
@@ -27,20 +27,22 @@ impl LintPass for NeedlessBool {
...
-                    span_lint(cx, NEEDLESS_BOOL, e.span,
-                              "you can reduce your if statement to `!` + its predicate"); },
-                (Option::Some(false), Option::Some(false)) => {
-                    span_lint(cx, NEEDLESS_BOOL, e.span,
-                              "your if-then-else expression will always return false"); },
+                              "this if-then-else expression will always return false"); },
+                (Some(true), Some(false)) => {
+                    span_lint(cx, NEEDLESS_BOOL, e.span, &format!(
+                        "you can reduce this if-then-else expression to just `{}`",
+                        snippet(cx, pred.span, ".."))); },
```
Comment (Manishearth) [inline src/needless_bool.rs]: if `snippet` actually defaults to `..`, we don't want to show it in this case (since its not part of a larger snippet)

Comment (birkenfeld) [inline src/needless_bool.rs]: Good point. In which case would the default actually be used? Is it a real situation or just an "avoid-Option-unwrap-default"?

Comment (Manishearth) [inline src/needless_bool.rs]: we can simply do `if snippet == '..'` and then span a lint talking about "predicates" instead.

File: src/needless_bool.rs [hunk 2]
```diff
@@ -27,20 +27,30 @@ impl LintPass for NeedlessBool {
...
-                              "you can reduce your if statement to its predicate"); },
-                (Option::Some(false), Option::Some(true)) => {
-                    span_lint(cx, NEEDLESS_BOOL, e.span,
-                              "you can reduce your if statement to `!` + its predicate"); },
-                (Option::Some(false), Option::Some(false)) => {
-                    span_lint(cx, NEEDLESS_BOOL, e.span,
-                              "your if-then-else expression will always return false"); },
+                              "this if-then-else expression will always return false"); },
+                (Some(true), Some(false)) => {
+                    let pred_snip = snippet(cx, pred.span, "..");
```
Comment (Manishearth) [inline src/needless_bool.rs]: Wait, why not just use `snippet(cx, pred.span, "its predicate")` for this whole chunk?

Comment (birkenfeld) [inline src/needless_bool.rs]: in that case it would be `reduce ... to just 'its predicate'` (with backticks instead of quotes), which looks like code.

Might work if we use something more obvious, like `"<predicate>"`.

Comment (Manishearth) [inline src/needless_bool.rs]: Ah, I see. Current code is fine then.

File: src/needless_bool.rs [hunk 3]
```diff
@@ -27,20 +27,30 @@ impl LintPass for NeedlessBool {
...
+                    let hint = if pred_snip == ".." { "its predicate".into() } else {
+                        format!("`{}`", pred_snip)
+                    };
+                    span_lint(cx, NEEDLESS_BOOL, e.span, &format!(
+                        "you can reduce this if-then-else expression to just {}", hint));
+                },
+                (Some(false), Some(true)) => {
+                    let pred_snip = snippet(cx, pred.span, "..");
+                    let hint = if pred_snip == ".." { "its predicate".into() } else {
```
Comment (Manishearth) [inline src/needless_bool.rs]: `!predicate`, right? the language should reflect that I guess.

**Comment by birkenfeld** [comment]
r?
